### ISSUE TITLE
Not doing anything after skip_1

### ISSUE THREAD

**Issue by ytbro00** [chaosking121/Grand-Order-Reroller#1]
So I've tried the included images, it's not working as said in instruction. I made my own screenshots and it only went up the intro with the training dummy. Even with my own screenshots it still wouldn't go through it.
I've also tried to end the training to reach skip_2 but then, still it doesn't detect anything.

Anything after skip_1 doesn't work for me for some reason. Any ideas?

Update: My modified monitor's color was the issue. It actually viewed all the screenshots I created as washed out colors. I reverted to the original colors and re calibrated it again and it worked.

**Comment by nisegami** [comment]
I replied to your email a bit ago (sorry I took so long), but I'll post the reply here as well: 

This is definitely a strange issue. I'm tempted to just say it's PyAutoGUI being fairly unreliable (which it is)  but if you're willing to give it a another chance, the objective behind choosing where to screenshot is finding something that changes as little as possible. Try making sure that you're not including any bits that change. For the attack button, make sure to not touch the cards at all. I had that problem a few times where I went a little too close to the cards.

**Comment by ytbro00** [comment]
Thanks, Chaos. I fixed it somehow just now after hours of trying to figure it out. lol. I accidentally came across it when I selected the old Windows Photo Viewer instead of my other image viewers and it showed my that the screenshots are actually washed out.

Though there is one minor inconvenience right now. The Clear GO Data only works once. Whenever I click it again, nothing happens. When I click the app details I see that it is indeed running. Simply reinstalling it doesn't work. I have to re-install the whole modified image along with the FGO APK and Clear Go Data apk.

**Comment by nisegami** [comment]
Try this series of steps in this exact order then let me know what happens:

1. Start with fresh image, either including the clear data apk or install it now.
2. Open Grand Order, get to the title screen, tap somewhere then accept the ToS and let it get to the start of the first battle. 
3. Open the multitasking menu, then swipe Grand Order away to close it.
4. Run the clear data apk.
5. Repeat step 2. 
6. Repeat step 3. 
7. Repeat step 4.
8. Launch Grand Order - do you need to accept the ToS?

**Comment by ytbro00** [comment]
I tried those steps. It does not let me accept the ToS. It actually does not reset it at all.

I'll probably try and reinstall memu after I backup my macro and see if anything works.

**Comment by nisegami** [comment]
Are you using [this ova](https://www.reddit.com/r/grandorder/comments/6jompd/modified_memu_image_with_fgo_na_preloaded_and/)?

**Comment by ytbro00** [comment]
Alright solved it somehow. Yup, I was using that one. What I did was reinstall my Memu emulator again, installed the Clear Go APK and ran the FGO that was not updated, cleared the data and install the update over it, ran it and cleared it again. So far everything looks like it's working now.

Thank you for your time and making this script. 👍
