### ISSUE TITLE
No rolls

### ISSUE THREAD

**Issue by AmakusaShirou** [chaosking121/Grand-Order-Reroller#12]
Hello! ^^ I am aware that this was posted a long time ago, but i have just installed the whole thing and after following the steps to a T (and with quite a bit of struggling as I am a complete n00b), i get no rolls after launching python main.py

Is it because the reroller doesn't work anymore or is it something I did? I mean, it looks like it recognises the command and all, but nothing happens.  Thank you! ^^

**Comment by nisegami** [comment]
When Memu got banned, I stopped supporting the project. Nox works well now, so it could be rewritten but I don't have the time or the incentive unfortuately.

**Comment by AmakusaShirou** [comment]
ooh i see. Memu works again (but it's not very stable lol). Well thank you for taking the time to answer! :D much appreciated.
