### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by DankSinatr** [chaosking121/Grand-Order-Reroller#13]
Certain steps such as "run pip install pyautogui numpy opencv-python" and "Open CMD/Shell as admin and cd into this repo." and even "Run python main.py" Aren't self explanatory for someone with no previous experience. I'm simply trying to make life easier for myself with these rerolls.

**Comment by nisegami** [comment]
That's mostly intentional, since it's easier to support experienced users. That said, this doesn't work at all anymore.
